{
	"next_topic_id": 2,
	"topic": [
		{
			"topic_id": 1,
			"title": "Could you tell me what wrong they are? I wanna run zeronet on vps.",
			"body": "apt-get install python-dev\napt-get install python-setuptools\napt-get install python-pip\npip install --upgrade pip\napt-get install msgpack-python\npip install msgpack-python --upgrade\napt-get install python-gevent \npip install gevent --upgrade\nwget --no-check-certificate https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz\ntar -xzvf master.tar.gz\ncd ZeroNet-master\nnohup python zeronet.py --ui_ip 0.0.0.0\n\n\n\n\n\n- Starting ZeroNet...\n[15:01:37] - OpenSSL loaded, version: 01000207F\n[15:01:37] - Version: 0.4.1 r1533, Python 2.7.12 (default, Jul  1 2016, 15:12:24) \n[GCC 5.4.0 20160609], Gevent: 1.1.0\n[15:01:37] - Creating FileServer....\n[15:01:37] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > _socket2.py line 228\n[15:01:37] - Creating UiServer....\n[15:01:37] - Removing old SSL certs...\n[15:01:37] - Starting servers....\n[15:01:37] Ui.UiServer --------------------------------------\n[15:01:37] Ui.UiServer Web interface: http://0.0.0.0:43110/\n[15:01:37] Ui.UiServer --------------------------------------\n[15:01:38] FileServer Checking port 15441 using portchecker.co...\n[15:01:40] FileServer [BAD :(] Port closed: Port 15441 is closed.\n[15:01:40] FileServer Trying to open port using UpnpPunch...\n[15:01:45] - Unhandled exception\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/gevent/greenlet.py\", line 534, in run\n    result = self._run(*self.args, **self.kwargs)\n  File \"src/File/FileServer.py\", line 190, in checkSites\n    self.openport()\n  File \"src/File/FileServer.py\", line 72, in openport\n    UpnpPunch.ask_to_open_port(self.port, 'ZeroNet', retries=3, protos=[\"TCP\"])\n  File \"src/util/UpnpPunch.py\", line 317, in ask_to_open_port\n    protos=protos)\n  File \"src/util/UpnpPunch.py\", line 296, in _communicate_with_igd\n    _orchestrate_soap_request(local_ip, port, fn, desc, protos)\n  File \"src/util/UpnpPunch.py\", line 271, in _orchestrate_soap_request\n    idg_data = _collect_idg_data(ip)\n  File \"src/util/UpnpPunch.py\", line 252, in _collect_idg_data\n    idg_response = perform_m_search(ip_addr)\n  File \"src/util/UpnpPunch.py\", line 48, in perform_m_search\n    sock.bind((local_ip, 10000))\n  File \"<string>\", line 1, in bind\nerror: [Errno 98] Address already in use\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/gevent/greenlet.py\", line 534, in run\n    result = self._run(*self.args, **self.kwargs)\n  File \"src/File/FileServer.py\", line 190, in checkSites\n    self.openport()\n  File \"src/File/FileServer.py\", line 72, in openport\n    UpnpPunch.ask_to_open_port(self.port, 'ZeroNet', retries=3, protos=[\"TCP\"])\n  File \"src/util/UpnpPunch.py\", line 317, in ask_to_open_port\n    protos=protos)\n  File \"src/util/UpnpPunch.py\", line 296, in _communicate_with_igd\n    _orchestrate_soap_request(local_ip, port, fn, desc, protos)\n  File \"src/util/UpnpPunch.py\", line 271, in _orchestrate_soap_request\n    idg_data = _collect_idg_data(ip)\n  File \"src/util/UpnpPunch.py\", line 252, in _collect_idg_data\n    idg_response = perform_m_search(ip_addr)\n  File \"src/util/UpnpPunch.py\", line 48, in perform_m_search\n    sock.bind((local_ip, 10000))\n  File \"<string>\", line 1, in bind\nsocket.error: [Errno 98] Address already in use",
			"added": 1475507525
		}
	],
	"topic_vote": {},
	"next_comment_id": 1,
	"comment": {},
	"comment_vote": {}
}